name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: ./w201_03_frontend
        run: npm install

      - name: Build frontend
        working-directory: ./w201_03_frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: ./w201_03_backend
        run: npm install

      # Step 6: Build backend
      - name: Build backend
        working-directory: ./w201_03_backend
        run: npm run build
