name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
        run:
            shell: bash

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}

      - name: Install frontend dependencies
        run: |
          echo "Building frontend..."
          cd ./w201_03_frontend
          npm install

      - name: Build frontend
        run: |
          cd ./w201_03_frontend
          npm run build

       - name: Install backend dependencies
        run: |
          echo "Building backend..."
          cd ./w201_03_backend
          npm install

      - name: Build backend
        run: |
          cd ./w201_03_backend
          npm run build
